version: '3.1'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_USER: root
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: test
    ports:
      - "3306:3306"