#spring:
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: ${DB_URL}
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
#  jpa:
#    hibernate:
#      ddl-auto: update
#  servlet:
#    multipart:
#      max-file-size: 30MB
#      max-request-size: 30MB
#  config:
#    import: application.properties

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/onboarding
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true #콘솔에 로그가 나옴
        format_sql: true #이쁘게 해줌
  data:
    web:
      pageable:
        default-page-size: 5

cloud:
  aws:
    s3:
      bucket: ${CLOUD_AWS_CREDENTIALS_BUCKET}
    credentials:
      access-key: ${CLOUD_AWS_CREDENTIALS_ACCESS_KEY}
      secret-key: ${CLOUD_AWS_CREDENTIALS_SECRET_KEY}
    stack:
      auto: false
    region:
      static: ${CLOUD_AWS_REGION_STATIC}
      auto: false

logging:
  level:
    root: INFO
    org.springframework: INFO
