spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/test?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: Abcd123@
  #  datasource:
  #    driver-class-name: org.h2.Driver
  #    url: jdbc:h2:mem:;MODE=MySQL
  #    username: root
  #    password: test_password

  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MariaDBDialect

logging:
  level:
    org.springframework.jdbc.datasource: DEBUG